// <auto-generated />
using System;
using BlogWebApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogWebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231110003744_Repositories")]
    partial class Repositories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4276796c-10ff-4544-b2f7-819d5bcc46fc"),
                            CategoryId = new Guid("0ebc1653-2b5f-4c28-b8fb-8de71c7d71cf"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt, enim eu facilisis condimentum, purus massa tristique felis, non congue nibh tortor at purus. Donec in viverra elit. Mauris eget velit non lacus porta mollis non id quam. Proin condimentum fermentum ornare. In lobortis tempus augue, a accumsan lectus molestie eu. Nulla facilisi. Nulla at pellentesque ante. Sed nec diam quis est tempor congue ac varius ante. Suspendisse ac massa vel quam ultricies suscipit. Quisque mi massa, vestibulum sed ultrices vel, varius consectetur lorem.",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2061),
                            ImageId = new Guid("94054bb5-2fd2-4b91-bf53-6077f0684025"),
                            IsDeleted = false,
                            Title = "Title",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = new Guid("880e2210-a262-45ad-992d-16ccc1708736"),
                            CategoryId = new Guid("82212532-f3e7-4e53-8d1a-8f8752dc054d"),
                            Content = "Nullam sed sapien turpis. Pellentesque quis neque nunc. Vivamus cursus et neque at posuere. Vivamus iaculis congue ipsum in commodo. Mauris quis ante condimentum, vulputate sem nec, facilisis velit. Fusce ligula nibh, finibus non elit porta, venenatis dictum massa. Aliquam vel quam at orci placerat tempor quis quis libero. Donec nec lacus purus.",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2084),
                            ImageId = new Guid("437587af-85d1-4a98-8467-35a878cceed1"),
                            IsDeleted = false,
                            Title = "Title",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ebc1653-2b5f-4c28-b8fb-8de71c7d71cf"),
                            CreatedBy = "AdminTest",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2237),
                            IsDeleted = false,
                            Name = "C# ASP.NET CORE MVC"
                        },
                        new
                        {
                            Id = new Guid("82212532-f3e7-4e53-8d1a-8f8752dc054d"),
                            CreatedBy = "TestAdmin",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2250),
                            IsDeleted = false,
                            Name = "Java Spring Boot"
                        });
                });

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94054bb5-2fd2-4b91-bf53-6077f0684025"),
                            CreatedBy = "AdminImageTest",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2325),
                            FileName = "FileNameTest",
                            FileType = "Jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("437587af-85d1-4a98-8467-35a878cceed1"),
                            CreatedBy = "AdminTestImage",
                            CreatedDate = new DateTime(2023, 11, 10, 3, 37, 44, 798, DateTimeKind.Local).AddTicks(2328),
                            FileName = "TestFileName",
                            FileType = "Png",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Article", b =>
                {
                    b.HasOne("BlogWebApp.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApp.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BlogWebApp.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
